use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

/// Logical native components whose integrity is enforced at startup.
/// The base name is the assembly / library name; the actual on-disk file is
/// resolved per target platform (`Foo.dll`, `Foo.dylib`, or `libFoo.so`).
///
/// This list is the *completeness* contract: if any component is missing from
/// `natives/` at build time the build fails loudly rather than shipping an app
/// that skips an integrity check.
const NATIVE_COMPONENTS: &[&str] = &[
    "ConnectionManager",
    "FileQueryEngine",
    "QueryExecutor",
    "QueryHistory",
    "SchemaExplorer",
    "SshTunnel",
    "duckdb",
    "sqlcipher",
];

fn native_ext() -> &'static str {
    // build.rs sees the *target* via CARGO_CFG_TARGET_OS, not the host.
    match std::env::var("CARGO_CFG_TARGET_OS").as_deref() {
        Ok("windows") => "dll",
        Ok("macos") => "dylib",
        _ => "so",
    }
}

/// Resolve a component base name to the real file in `natives/`, accepting both
/// the bare `name.ext` and the unix `libname.ext` convention.
fn resolve_native(natives: &Path, base: &str, ext: &str) -> Option<PathBuf> {
    let plain = natives.join(format!("{base}.{ext}"));
    if plain.exists() {
        return Some(plain);
    }
    let prefixed = natives.join(format!("lib{base}.{ext}"));
    if prefixed.exists() {
        return Some(prefixed);
    }
    None
}

fn generate_dll_hashes() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"),
    );
    let natives = manifest_dir.join("natives");
    let ext = native_ext();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — DO NOT EDIT.\n");
    out.push_str("// SHA-256 of every native library shipped in natives/, computed at build\n");
    out.push_str("// time from the exact bytes that will ship. Single source of truth for the\n");
    out.push_str("// startup integrity check; never hand-maintained (code audit C-3).\n");
    out.push_str("pub static DLL_HASHES: &[(&str, &str)] = &[\n");

    for base in NATIVE_COMPONENTS {
        let path = resolve_native(&natives, base, ext).unwrap_or_else(|| {
            panic!(
                "build.rs: required native library for component `{base}` not found in {} \
                 (looked for `{base}.{ext}` and `lib{base}.{ext}`). Publish the C# projects \
                 and stage the prebuilt natives before building the Tauri app.",
                natives.display()
            )
        });

        // Regenerate whenever this binary changes — eliminates the stale-hash bug class.
        println!("cargo:rerun-if-changed={}", path.display());

        let bytes = fs::read(&path)
            .unwrap_or_else(|e| panic!("build.rs: cannot read {}: {e}", path.display()));
        let hash = hex::encode(Sha256::digest(&bytes));
        let file_name = path
            .file_name()
            .expect("native path has a file name")
            .to_string_lossy()
            .into_owned();

        // {:?} emits a correctly-escaped Rust string literal.
        out.push_str(&format!("    ({file_name:?}, {hash:?}),\n"));
    }

    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("dll_hashes.rs");
    fs::write(&out_path, out)
        .unwrap_or_else(|e| panic!("build.rs: cannot write {}: {e}", out_path.display()));

    // Rebuild if a native is added to / removed from the directory.
    println!("cargo:rerun-if-changed={}", natives.display());
}

fn main() {
    generate_dll_hashes();
    tauri_build::build();
}
