[connection]
name = "Read ONly Test"
engine = "sqlite"
host = "localhost"
port = 3306
database = "test_readonly.db"
username = "root"
credential_ref = "devsql:read-only-test:root"
ssl_mode = "prefer"
read_only = true

[display]
color = "#61ff7b"
group = ""