<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <NativeLib>Shared</NativeLib>
    <SelfContained>true</SelfContained>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="System.Data.Odbc" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Shared/NativeString.cs" Link="NativeString.cs" />
    <Compile Include="../Shared/SqliteConnectionString.cs" Link="SqliteConnectionString.cs" />
    <Compile Include="../Shared/DuckDbTableBuilder.cs" Link="DuckDbTableBuilder.cs" />
    <Compile Include="../Shared/DuckDbFileScan.cs" Link="DuckDbFileScan.cs" />
  </ItemGroup>
</Project>
